"""
    SDX LC

    SDX Topology validation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: lmarinve@fiu.edu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.patch_users_user_id_request import PatchUsersUserIdRequest


class TestPatchUsersUserIdRequest(unittest.TestCase):
    """PatchUsersUserIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchUsersUserIdRequest(self):
        """Test PatchUsersUserIdRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchUsersUserIdRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
