"""
    SDX LC

    SDX Topology validation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: lmarinve@fiu.edu
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_topology(self):
        """Test case for delete_topology

        Delete a Topology  # noqa: E501
        """
        pass

    def test_get_user_user_id(self):
        """Test case for get_user_user_id

        Get User Info by User ID  # noqa: E501
        """
        pass

    def test_patch_users_user_id(self):
        """Test case for patch_users_user_id

        Update User Information  # noqa: E501
        """
        pass

    def test_post_user(self):
        """Test case for post_user

        Create New User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
