"""
    SDX LC

    SDX Topology validation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: lmarinve@fiu.edu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.port import Port


class TestPort(unittest.TestCase):
    """Port unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPort(self):
        """Test Port"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Port()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
