# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_name=None, first_name=None, last_name=None, email=None, password=None):  # noqa: E501
        """InlineObject1 - a model defined in OpenAPI

        :param user_name: The user_name of this InlineObject1.  # noqa: E501
        :type user_name: str
        :param first_name: The first_name of this InlineObject1.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this InlineObject1.  # noqa: E501
        :type last_name: str
        :param email: The email of this InlineObject1.  # noqa: E501
        :type email: str
        :param password: The password of this InlineObject1.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'user_name': str,
            'first_name': str,
            'last_name': str,
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'user_name': 'user_name',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
            'password': 'password'
        }

        self._user_name = user_name
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_1 of this InlineObject1.  # noqa: E501
        :rtype: InlineObject1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_name(self):
        """Gets the user_name of this InlineObject1.


        :return: The user_name of this InlineObject1.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this InlineObject1.


        :param user_name: The user_name of this InlineObject1.
        :type user_name: str
        """
        if user_name is None:
            raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501

        self._user_name = user_name

    @property
    def first_name(self):
        """Gets the first_name of this InlineObject1.


        :return: The first_name of this InlineObject1.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this InlineObject1.


        :param first_name: The first_name of this InlineObject1.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this InlineObject1.


        :return: The last_name of this InlineObject1.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this InlineObject1.


        :param last_name: The last_name of this InlineObject1.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this InlineObject1.


        :return: The email of this InlineObject1.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this InlineObject1.


        :param email: The email of this InlineObject1.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password(self):
        """Gets the password of this InlineObject1.


        :return: The password of this InlineObject1.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this InlineObject1.


        :param password: The password of this InlineObject1.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
